# Generated by Django 4.2.3 on 2023-11-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_appointments_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='plate',
            field=models.TextField(),
        ),
    ]
