# Generated by Django 4.2.3 on 2023-11-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_alter_cars_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='state',
            field=models.CharField(choices=[('CANCELAR', 'Cancelar'), ('PENDIENTE', 'Pendiente'), ('PROCESO', 'Proceso'), ('REPARADO', 'Reparado')], max_length=9),
        ),
    ]
