# Generated by Django 4.2.3 on 2023-11-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_alter_appointments_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='observations',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='observations',
            new_name='observation',
        ),
    ]
