# Generated by Django 4.2.3 on 2023-11-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_rename_observations_appointments_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
